### PR TITLE
Revert "Added Dutch translation"

### PR DESCRIPTION
**Pull request by alexkdeveloper**

### CODE REVIEW

**Comment by Vistaus** [comment]
Why?

**Comment by alexkdeveloper** [comment]
po files are missing. Builder shows an error. You can create a new PR if you want to add a translation.

**Comment by Vistaus** [comment]
Missing? But the po file was there…

**Comment by alexkdeveloper** [comment]
Pot files were found in an existing PR. These are templates for creating po files. You can replace the pot extension with po.

**Comment by alexkdeveloper** [comment]
I have renamed the necessary files. The test build was successful!

**Pull request merged**
